### ISSUE TITLE
With 2.2.1 i have a new selectable profile ```x¦j_Ì¢```

### ISSUE THREAD

**Issue by Animal-UK** [surrim/moos21#5]
With 2.2.1 i have a new selectable profile `x¦j_Ì¢`

https://cdn.discordapp.com/attachments/1094430395698774066/1100814260067631154/image.png

**Comment by surrim** [comment]
Fixed with commit https://github.com/surrim/moos21/commit/165cfee04a21212321c411033f602b4e375ec309
